version: "3.8"

services:
  # webapi:
  #   container_name: webapi
  #   build:
  #     context: .
  #     dockerfile: src/webapi/Dockerfile
  #   depends_on:
  #     - redis-svc
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - DOTNET_RUNNING_IN_COMPOSE=${DOTNET_RUNNING_IN_COMPOSE}

  # seq-svc:
  #   image: datalust/seq
  #   container_name: seq-svc
  #   restart: always
  #   ports:
  #     - 5342:80 #web ui
  #     - 5341:5341 #ingestion
  #   volumes:
  #     - ./.docker-compose/seq:/data
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - BASE_URI=http://seq-svc:5342

  redis-svc:
    container_name: redis-svc
    image: redis
    #image: redis:alpine
    #image: bitnami/redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]
    #entrypoint: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./.docker-compose/redis:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  p3x:
    container_name: redisui
    image: patrikx3/p3x-redis-ui
    ports:
      - 7843:7843
    volumes:
      - ./.docker-compose/p3x-redis-ui-settings:/settings
    restart: always
    depends_on:
      - redis-svc
